### ISSUE TITLE
Permissions issues Mac

### ISSUE THREAD

**Issue by gulien** [thecodingmachine/kickoff-docker-php#41]
As on Linux, I should bind the UID from the current host user with the UID from the www-data user in the NGINX and PHP-FPM containers.

OR: this is a Docker Sync related issue.

OR: both.

Also, the GID may not be necessary to bind.

Current workaround on Mac:

* Add the following at the end of `orbit.yml`:

```yaml
- use: "restore"
    run:
      - orbit run command-restore-permissions -c config/orbit/orbit-commands.yml -v Project,config/project.yml;Modules,config/modules.yml -e Config,config/.env
```

* Add the following at the end of `config/orbit/orbit-commands.yml`:

```yaml
  # |--------------------------------------------------------------------------
  # | orbit run command-restore-permissions
  # |--------------------------------------------------------------------------
  # |
  # | Fixes the permissions by running
  # | "chown -R www-data:www-data /var/www/html" inside the PHP-FPM container.
  # |

  - use: "command-restore-permissions"
    run:
       - docker exec --user root -ti {{ .EnvFiles.Config.ENV }}-{{ .Values.Project.name }}-php-fpm chown -R www-data:www-data /var/www/html
```
