### ISSUE TITLE
The UID variable is not set. Defaulting to a blank string.

### ISSUE THREAD

**Issue by ghost** [thecodingmachine/kickoff-docker-php#54]
Was having issues getting the base package up and running, managed to resolve it myself but thought I would feedback the issues (MacOS, followed quick start, using docker-sync).

First, I don't know if UID is meant to automatically get set - but it wasn't. I ended up manually adding it to the .env file with my UID. That resolved it, so if it's intended to set the UID manually perhaps include that in the guide.

Second, my path had a space in it which was tripping the fix-permissions.sh file. I wrapped the second part of each sedi command with "" to resolve.

Apart from that it spun up fine - thanks a lot for a great looking package!

**Comment by gulien** [comment]
Hi @ChrisB-io!

Thank you for your feedback 😃 

Actually, the UID is meant to automatically get set.

The script `fix-permissions.sh` is setting the UID by replacing the variable `${UID}` in the following files:

*  `${ROOT}/modules/nginx/docker-compose.yml`
* `${ROOT}/modules/php-fpm/docker-compose.yml`
* `${ROOT}/docker-sync.yml`

As your PATH had a white space, I guess the script failed to run the `sed -i` command.

As I understand, you've replaced for example `sedi "s/\${UID}/$NEW_UID/g" ${ROOT}/modules/nginx/docker-compose.yml;` with `sedi "s/\${UID}/$NEW_UID/g" "${ROOT}/modules/nginx/docker-compose.yml";`?

Feel free to open a PR 👍 😄

**Comment by ghost** [comment]
Hey @gulien, have submitted a PR for you. Tested and executed flawlessly.

I'm trying to utilise this for WordPress environments, looks like I have a number of hurdles ahead of me though (php version, mysqli, nginx config...)

**Comment by gulien** [comment]
Thanks again @ChrisB-io for your PR!

May I suggest using a more simple stack?

For example, you may consider using one of the images provided here: https://github.com/thecodingmachine/docker-images-php
It allows you to set automatically the PHP extensions you need and so on!

With a simple `docker-compose.yml` file:

```yaml
version: '3.3'

services:

  traefik:
    image: traefik:1.5.3-alpine
    container_name: traefik_local
    restart: "no"
    command: --docker --logLevel=ERROR
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/traefik/traefik.local.toml:/traefik.toml:ro # see kickoff-docker-php/modules/traefik/traefik.blueprint.toml

  phpapache:
    image: thecodingmachine/php:7.2-v1-apache
    container_name: phpapache_local
    restart: "no"
    labels:
      - traefik.backend=phpapache
      - traefik.frontend.rule=Host:yourproject.local
    environment:
      - APACHE_DOCUMENT_ROOT=public/ # or whatever directory used by WordPress
    volumes:
      - ./src:/var/www/html:rw

  mysql:
    image: mysql:5.7
    container_name: mysql_local
    restart: "no"
    labels:
      - traefik.enable=false
    environment:
      - MYSQL_USER=auser
      - MYSQL_DATABASE=db
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - mysql_local_data:/var/lib/mysql
      - ./services/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro # see kickoff-docker-php/modules/mysql/conf.d/utf8mb4.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: phpmyadmin_local
    restart: "no"
    labels:
      - traefik.backend=phpadmin
      - traefik.frontend.rule=Host:phpadmin.yourproject.local
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=admin
    volumes:
      - phpmyadmin_local_data:/sessions

volumes:

    mysql_local_data:
      driver: local

    phpmyadmin_local_data:
      driver: local
```

And the command `docker-compose up -d`, you're good to go!

If you need to access your PHP logs, simply run `docker logs -f phpapache_local`.
If you need to access a workspace, run `docker exec -ti phpapache_local bash`.

Of course, you may also use [Orbit](https://github.com/gulien/orbit) if you need to do some templating according to your current environment and / or shortcuts commands 😃
